// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getAccountBalance = `-- name: GetAccountBalance :one
SELECT (COALESCE(SUM(debit), 0) - COALESCE(SUM(credit), 0))::numeric AS balance
FROM entries
WHERE account_id = $1
`

// Balance is DERIVED, never stored: Σdebit − Σcredit over the account's entries. Cast to
// numeric (not float) so the type is exact and deterministic; asset accounts read positive
// (debit-normal), liability & revenue negative.
func (q *Queries) GetAccountBalance(ctx context.Context, accountID uuid.UUID) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getAccountBalance, accountID)
	var balance pgtype.Numeric
	err := row.Scan(&balance)
	return balance, err
}

const getOrCreatePerRefAccount = `-- name: GetOrCreatePerRefAccount :one
INSERT INTO accounts (merchant_id, type, kind, currency, reference_id)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (merchant_id, kind, currency, reference_id) WHERE reference_id IS NOT NULL
DO UPDATE SET kind = EXCLUDED.kind
RETURNING id, merchant_id, type, kind, currency, reference_id, created_at
`

type GetOrCreatePerRefAccountParams struct {
	MerchantID  uuid.UUID  `json:"merchant_id"`
	Type        string     `json:"type"`
	Kind        string     `json:"kind"`
	Currency    string     `json:"currency"`
	ReferenceID *uuid.UUID `json:"reference_id"`
}

// Same insert-first discipline for a per-reference account (reference_id set), e.g. a per-intent
// escrow_liability in M3. Same DO UPDATE ... RETURNING race-safety as above, different index.
func (q *Queries) GetOrCreatePerRefAccount(ctx context.Context, arg GetOrCreatePerRefAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, getOrCreatePerRefAccount,
		arg.MerchantID,
		arg.Type,
		arg.Kind,
		arg.Currency,
		arg.ReferenceID,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Type,
		&i.Kind,
		&i.Currency,
		&i.ReferenceID,
		&i.CreatedAt,
	)
	return i, err
}

const getOrCreateSingletonAccount = `-- name: GetOrCreateSingletonAccount :one
INSERT INTO accounts (merchant_id, type, kind, currency)
VALUES ($1, $2, $3, $4)
ON CONFLICT (merchant_id, kind, currency) WHERE reference_id IS NULL
DO UPDATE SET kind = EXCLUDED.kind
RETURNING id, merchant_id, type, kind, currency, reference_id, created_at
`

type GetOrCreateSingletonAccountParams struct {
	MerchantID uuid.UUID `json:"merchant_id"`
	Type       string    `json:"type"`
	Kind       string    `json:"kind"`
	Currency   string    `json:"currency"`
}

// Insert-first get-or-create for a singleton account (reference_id IS NULL), e.g. platform_cash.
// The INSERT runs first and the partial unique index arbitrates any race between concurrent
// creators — never SELECT-then-INSERT (a TOCTOU race). On conflict we DO UPDATE (a no-op that
// re-sets kind to itself) rather than DO NOTHING: DO UPDATE ... RETURNING always yields the live
// row, whereas DO NOTHING + a UNION-ed SELECT returns ZERO rows when the losing txn's snapshot
// predates the winner's commit (READ COMMITTED) — a real race that surfaced as a spurious
// ErrNoRows on a merchant's first concurrent capture.
func (q *Queries) GetOrCreateSingletonAccount(ctx context.Context, arg GetOrCreateSingletonAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, getOrCreateSingletonAccount,
		arg.MerchantID,
		arg.Type,
		arg.Kind,
		arg.Currency,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Type,
		&i.Kind,
		&i.Currency,
		&i.ReferenceID,
		&i.CreatedAt,
	)
	return i, err
}

const listAccounts = `-- name: ListAccounts :many
SELECT id, merchant_id, type, kind, currency, reference_id, created_at FROM accounts
WHERE merchant_id = $1
ORDER BY created_at
`

func (q *Queries) ListAccounts(ctx context.Context, merchantID uuid.UUID) ([]Account, error) {
	rows, err := q.db.Query(ctx, listAccounts, merchantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.Type,
			&i.Kind,
			&i.Currency,
			&i.ReferenceID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
