// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_keys.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countKeysForMerchant = `-- name: CountKeysForMerchant :one
SELECT count(*) FROM api_keys WHERE merchant_id = $1
`

// Used by the dev seed to stay idempotent (only insert keys if a merchant has none yet).
func (q *Queries) CountKeysForMerchant(ctx context.Context, merchantID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countKeysForMerchant, merchantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getKeysByPrefix = `-- name: GetKeysByPrefix :many
SELECT id, merchant_id, kind, token_prefix, token_hash, created_at, revoked_at FROM api_keys
WHERE token_prefix = $1 AND revoked_at IS NULL
`

// Narrow to candidate keys by the indexed, non-secret prefix; the caller then compares the
// full-token hash in constant time. Revoked keys are excluded here so they can never match.
func (q *Queries) GetKeysByPrefix(ctx context.Context, tokenPrefix string) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, getKeysByPrefix, tokenPrefix)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiKey
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.Kind,
			&i.TokenPrefix,
			&i.TokenHash,
			&i.CreatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertAPIKey = `-- name: InsertAPIKey :one
INSERT INTO api_keys (merchant_id, kind, token_prefix, token_hash)
VALUES ($1, $2, $3, $4)
RETURNING id, merchant_id, kind, token_prefix, token_hash, created_at, revoked_at
`

type InsertAPIKeyParams struct {
	MerchantID  uuid.UUID `json:"merchant_id"`
	Kind        string    `json:"kind"`
	TokenPrefix string    `json:"token_prefix"`
	TokenHash   string    `json:"token_hash"`
}

func (q *Queries) InsertAPIKey(ctx context.Context, arg InsertAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, insertAPIKey,
		arg.MerchantID,
		arg.Kind,
		arg.TokenPrefix,
		arg.TokenHash,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Kind,
		&i.TokenPrefix,
		&i.TokenHash,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}
