// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: idempotency.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteKey = `-- name: DeleteKey :exec
DELETE FROM idempotency_keys
WHERE id = $1
`

// Release a claim whose handler produced a transient (5xx/panic) result, so a retry can re-run
// rather than being wedged replaying a server error. Scoped by id for the same reason as above.
func (q *Queries) DeleteKey(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteKey, id)
	return err
}

const expireCompleted = `-- name: ExpireCompleted :exec
DELETE FROM idempotency_keys
WHERE status = 'completed' AND created_at < $1
`

// Enforce the ~24h key lifetime (see nem_pay/CLAUDE.md): drop completed rows past the cutoff
// so the table stays bounded and a key legitimately reused after its lifetime runs fresh
// rather than replaying a stale response.
func (q *Queries) ExpireCompleted(ctx context.Context, createdAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, expireCompleted, createdAt)
	return err
}

const getByKey = `-- name: GetByKey :one
SELECT id, merchant_id, idem_key, request_hash, status, response_code, response_body, locked_at, created_at FROM idempotency_keys
WHERE merchant_id = $1 AND idem_key = $2
`

type GetByKeyParams struct {
	MerchantID uuid.UUID `json:"merchant_id"`
	IdemKey    string    `json:"idem_key"`
}

// Read the existing claim after a 23505, to decide replay (completed + same hash) vs
// 409 (still in_flight) vs 422 (same key, different request).
func (q *Queries) GetByKey(ctx context.Context, arg GetByKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, getByKey, arg.MerchantID, arg.IdemKey)
	var i IdempotencyKey
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.IdemKey,
		&i.RequestHash,
		&i.Status,
		&i.ResponseCode,
		&i.ResponseBody,
		&i.LockedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertInFlight = `-- name: InsertInFlight :one
INSERT INTO idempotency_keys (merchant_id, idem_key, request_hash, status)
VALUES ($1, $2, $3, 'in_flight')
RETURNING id, merchant_id, idem_key, request_hash, status, response_code, response_body, locked_at, created_at
`

type InsertInFlightParams struct {
	MerchantID  uuid.UUID `json:"merchant_id"`
	IdemKey     string    `json:"idem_key"`
	RequestHash string    `json:"request_hash"`
}

// Insert-first claim of an idempotency key. Runs BEFORE the handler; the UNIQUE constraint
// arbitrates concurrent retries (the loser gets 23505, never a raced SELECT). Committed on
// its own so the claim is visible immediately to a competing request — that visibility is
// the whole point, and the reason this is not folded into the handler's money tx.
func (q *Queries) InsertInFlight(ctx context.Context, arg InsertInFlightParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, insertInFlight, arg.MerchantID, arg.IdemKey, arg.RequestHash)
	var i IdempotencyKey
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.IdemKey,
		&i.RequestHash,
		&i.Status,
		&i.ResponseCode,
		&i.ResponseBody,
		&i.LockedAt,
		&i.CreatedAt,
	)
	return i, err
}

const markCompleted = `-- name: MarkCompleted :exec
UPDATE idempotency_keys
SET status = 'completed', response_code = $2, response_body = $3
WHERE id = $1
`

type MarkCompletedParams struct {
	ID           uuid.UUID `json:"id"`
	ResponseCode *int32    `json:"response_code"`
	ResponseBody []byte    `json:"response_body"`
}

// Store the first caller's final response (raw bytes) so retries replay it byte-for-byte.
// Scoped by id (the row THIS request inserted), so it can never stamp a different row that a
// sweeper deleted-and-a-retry-recreated under the same (merchant_id, idem_key).
func (q *Queries) MarkCompleted(ctx context.Context, arg MarkCompletedParams) error {
	_, err := q.db.Exec(ctx, markCompleted, arg.ID, arg.ResponseCode, arg.ResponseBody)
	return err
}

const resetOrphans = `-- name: ResetOrphans :exec
DELETE FROM idempotency_keys
WHERE status = 'in_flight' AND locked_at < $1
`

// Crash recovery: free rows stuck 'in_flight' past the cutoff. Without this, a crash mid
// request pins every later retry at 409 forever.
func (q *Queries) ResetOrphans(ctx context.Context, lockedAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, resetOrphans, lockedAt)
	return err
}
