// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ledger.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const insertEntry = `-- name: InsertEntry :one
INSERT INTO entries (transaction_id, account_id, debit, credit, currency)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, transaction_id, account_id, debit, credit, currency, created_at
`

type InsertEntryParams struct {
	TransactionID uuid.UUID `json:"transaction_id"`
	AccountID     uuid.UUID `json:"account_id"`
	Debit         int64     `json:"debit"`
	Credit        int64     `json:"credit"`
	Currency      string    `json:"currency"`
}

// One leg of a transaction. The table's CHECK guarantees exactly one of debit/credit is
// non-zero and both are non-negative — malformed legs are impossible to persist.
func (q *Queries) InsertEntry(ctx context.Context, arg InsertEntryParams) (Entry, error) {
	row := q.db.QueryRow(ctx, insertEntry,
		arg.TransactionID,
		arg.AccountID,
		arg.Debit,
		arg.Credit,
		arg.Currency,
	)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.TransactionID,
		&i.AccountID,
		&i.Debit,
		&i.Credit,
		&i.Currency,
		&i.CreatedAt,
	)
	return i, err
}

const insertTransaction = `-- name: InsertTransaction :one
INSERT INTO transactions (merchant_id, kind, reference_id)
VALUES ($1, $2, $3)
RETURNING id, merchant_id, kind, reference_id, created_at
`

type InsertTransactionParams struct {
	MerchantID  uuid.UUID  `json:"merchant_id"`
	Kind        string     `json:"kind"`
	ReferenceID *uuid.UUID `json:"reference_id"`
}

// One row per money event (capture/settle/refund, later release). The balanced entries
// that make it sum to zero are inserted separately, all inside the caller's DB tx.
func (q *Queries) InsertTransaction(ctx context.Context, arg InsertTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, insertTransaction, arg.MerchantID, arg.Kind, arg.ReferenceID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Kind,
		&i.ReferenceID,
		&i.CreatedAt,
	)
	return i, err
}
