// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: merchants.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createMerchant = `-- name: CreateMerchant :one
INSERT INTO merchants (name) VALUES ($1) RETURNING id, name, created_at
`

func (q *Queries) CreateMerchant(ctx context.Context, name string) (Merchant, error) {
	row := q.db.QueryRow(ctx, createMerchant, name)
	var i Merchant
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getMerchant = `-- name: GetMerchant :one
SELECT id, name, created_at FROM merchants WHERE id = $1
`

func (q *Queries) GetMerchant(ctx context.Context, id uuid.UUID) (Merchant, error) {
	row := q.db.QueryRow(ctx, getMerchant, id)
	var i Merchant
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}
