// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID          uuid.UUID          `json:"id"`
	MerchantID  uuid.UUID          `json:"merchant_id"`
	Type        string             `json:"type"`
	Kind        string             `json:"kind"`
	Currency    string             `json:"currency"`
	ReferenceID *uuid.UUID         `json:"reference_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type ApiKey struct {
	ID          uuid.UUID          `json:"id"`
	MerchantID  uuid.UUID          `json:"merchant_id"`
	Kind        string             `json:"kind"`
	TokenPrefix string             `json:"token_prefix"`
	TokenHash   string             `json:"token_hash"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	RevokedAt   pgtype.Timestamptz `json:"revoked_at"`
}

type Entry struct {
	ID            uuid.UUID          `json:"id"`
	TransactionID uuid.UUID          `json:"transaction_id"`
	AccountID     uuid.UUID          `json:"account_id"`
	Debit         int64              `json:"debit"`
	Credit        int64              `json:"credit"`
	Currency      string             `json:"currency"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type IdempotencyKey struct {
	ID           uuid.UUID          `json:"id"`
	MerchantID   uuid.UUID          `json:"merchant_id"`
	IdemKey      string             `json:"idem_key"`
	RequestHash  string             `json:"request_hash"`
	Status       string             `json:"status"`
	ResponseCode *int32             `json:"response_code"`
	ResponseBody []byte             `json:"response_body"`
	LockedAt     pgtype.Timestamptz `json:"locked_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Merchant struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Outbox struct {
	ID            uuid.UUID          `json:"id"`
	MerchantID    uuid.UUID          `json:"merchant_id"`
	EventID       uuid.UUID          `json:"event_id"`
	EventType     string             `json:"event_type"`
	Payload       []byte             `json:"payload"`
	Status        string             `json:"status"`
	Attempts      int32              `json:"attempts"`
	NextAttemptAt pgtype.Timestamptz `json:"next_attempt_at"`
	LastError     *string            `json:"last_error"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type PaymentIntent struct {
	ID             uuid.UUID          `json:"id"`
	MerchantID     uuid.UUID          `json:"merchant_id"`
	Amount         int64              `json:"amount"`
	Currency       string             `json:"currency"`
	Status         string             `json:"status"`
	SettlementMode string             `json:"settlement_mode"`
	PayeeID        *uuid.UUID         `json:"payee_id"`
	ApplicationFee *int64             `json:"application_fee"`
	Metadata       []byte             `json:"metadata"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Transaction struct {
	ID          uuid.UUID          `json:"id"`
	MerchantID  uuid.UUID          `json:"merchant_id"`
	Kind        string             `json:"kind"`
	ReferenceID *uuid.UUID         `json:"reference_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type WebhookDelivery struct {
	ID         uuid.UUID          `json:"id"`
	OutboxID   uuid.UUID          `json:"outbox_id"`
	Attempt    int32              `json:"attempt"`
	StatusCode *int32             `json:"status_code"`
	Ok         bool               `json:"ok"`
	Error      *string            `json:"error"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type WebhookEndpoint struct {
	ID         uuid.UUID          `json:"id"`
	MerchantID uuid.UUID          `json:"merchant_id"`
	Url        string             `json:"url"`
	Secret     string             `json:"secret"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	DisabledAt pgtype.Timestamptz `json:"disabled_at"`
}
