// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outbox.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimDueOutbox = `-- name: ClaimDueOutbox :many
UPDATE outbox
SET next_attempt_at = now() + make_interval(secs => $1::double precision)
WHERE id IN (
  SELECT id FROM outbox
  WHERE status = 'pending' AND next_attempt_at <= now()
  ORDER BY next_attempt_at
  FOR UPDATE SKIP LOCKED
  LIMIT $2
)
RETURNING id, merchant_id, event_id, event_type, payload, status, attempts, next_attempt_at, last_error, created_at
`

type ClaimDueOutboxParams struct {
	LeaseSeconds float64 `json:"lease_seconds"`
	Lim          int32   `json:"lim"`
}

// The dispatcher's claim: due rows (pending, next_attempt_at reached), skip-locked so multiple
// dispatchers never grab the same row, and leased forward (next_attempt_at += lease) so a row
// isn't re-claimed while its delivery is in flight. If delivery crashes, the lease lapses and the
// row becomes due again — at-least-once by construction.
func (q *Queries) ClaimDueOutbox(ctx context.Context, arg ClaimDueOutboxParams) ([]Outbox, error) {
	rows, err := q.db.Query(ctx, claimDueOutbox, arg.LeaseSeconds, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Outbox
	for rows.Next() {
		var i Outbox
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.EventID,
			&i.EventType,
			&i.Payload,
			&i.Status,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.LastError,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOutbox = `-- name: GetOutbox :one
SELECT id, merchant_id, event_id, event_type, payload, status, attempts, next_attempt_at, last_error, created_at FROM outbox WHERE id = $1
`

func (q *Queries) GetOutbox(ctx context.Context, id uuid.UUID) (Outbox, error) {
	row := q.db.QueryRow(ctx, getOutbox, id)
	var i Outbox
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.EventID,
		&i.EventType,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.LastError,
		&i.CreatedAt,
	)
	return i, err
}

const insertDelivery = `-- name: InsertDelivery :exec
INSERT INTO webhook_deliveries (outbox_id, attempt, status_code, ok, error)
VALUES ($1, $2, $3, $4, $5)
`

type InsertDeliveryParams struct {
	OutboxID   uuid.UUID `json:"outbox_id"`
	Attempt    int32     `json:"attempt"`
	StatusCode *int32    `json:"status_code"`
	Ok         bool      `json:"ok"`
	Error      *string   `json:"error"`
}

// One row per delivery attempt (the delivery log).
func (q *Queries) InsertDelivery(ctx context.Context, arg InsertDeliveryParams) error {
	_, err := q.db.Exec(ctx, insertDelivery,
		arg.OutboxID,
		arg.Attempt,
		arg.StatusCode,
		arg.Ok,
		arg.Error,
	)
	return err
}

const insertOutbox = `-- name: InsertOutbox :one
INSERT INTO outbox (merchant_id, event_id, event_type, payload)
VALUES ($1, $2, $3, $4)
RETURNING id, merchant_id, event_id, event_type, payload, status, attempts, next_attempt_at, last_error, created_at
`

type InsertOutboxParams struct {
	MerchantID uuid.UUID `json:"merchant_id"`
	EventID    uuid.UUID `json:"event_id"`
	EventType  string    `json:"event_type"`
	Payload    []byte    `json:"payload"`
}

// Called INSIDE the money tx (with the caller's *Queries bound to that tx) so the event is
// written atomically with the state change it announces.
func (q *Queries) InsertOutbox(ctx context.Context, arg InsertOutboxParams) (Outbox, error) {
	row := q.db.QueryRow(ctx, insertOutbox,
		arg.MerchantID,
		arg.EventID,
		arg.EventType,
		arg.Payload,
	)
	var i Outbox
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.EventID,
		&i.EventType,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.LastError,
		&i.CreatedAt,
	)
	return i, err
}

const markOutboxDead = `-- name: MarkOutboxDead :exec
UPDATE outbox
SET attempts = attempts + 1, status = 'dead', last_error = $2
WHERE id = $1
`

type MarkOutboxDeadParams struct {
	ID        uuid.UUID `json:"id"`
	LastError *string   `json:"last_error"`
}

// Give up after the max attempts: park the row in 'dead' (a poison message can't wedge the queue).
func (q *Queries) MarkOutboxDead(ctx context.Context, arg MarkOutboxDeadParams) error {
	_, err := q.db.Exec(ctx, markOutboxDead, arg.ID, arg.LastError)
	return err
}

const markOutboxDelivered = `-- name: MarkOutboxDelivered :exec
UPDATE outbox SET status = 'delivered' WHERE id = $1
`

func (q *Queries) MarkOutboxDelivered(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markOutboxDelivered, id)
	return err
}

const markOutboxRetry = `-- name: MarkOutboxRetry :exec
UPDATE outbox
SET attempts = attempts + 1, next_attempt_at = $2, last_error = $3
WHERE id = $1
`

type MarkOutboxRetryParams struct {
	ID            uuid.UUID          `json:"id"`
	NextAttemptAt pgtype.Timestamptz `json:"next_attempt_at"`
	LastError     *string            `json:"last_error"`
}

// A failed attempt: bump attempts, schedule the next try (backoff computed by the caller), record
// the error. Stays 'pending' so the dispatcher re-claims it after next_attempt_at.
func (q *Queries) MarkOutboxRetry(ctx context.Context, arg MarkOutboxRetryParams) error {
	_, err := q.db.Exec(ctx, markOutboxRetry, arg.ID, arg.NextAttemptAt, arg.LastError)
	return err
}
