// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payment_intents.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createIntent = `-- name: CreateIntent :one
INSERT INTO payment_intents (merchant_id, amount, currency, settlement_mode, payee_id, application_fee, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, merchant_id, amount, currency, status, settlement_mode, payee_id, application_fee, metadata, created_at, updated_at
`

type CreateIntentParams struct {
	MerchantID     uuid.UUID  `json:"merchant_id"`
	Amount         int64      `json:"amount"`
	Currency       string     `json:"currency"`
	SettlementMode string     `json:"settlement_mode"`
	PayeeID        *uuid.UUID `json:"payee_id"`
	ApplicationFee *int64     `json:"application_fee"`
	Metadata       []byte     `json:"metadata"`
}

// Create a payment intent in its initial 'created' state. payee_id / application_fee are set only
// for escrow mode (NULL for direct).
func (q *Queries) CreateIntent(ctx context.Context, arg CreateIntentParams) (PaymentIntent, error) {
	row := q.db.QueryRow(ctx, createIntent,
		arg.MerchantID,
		arg.Amount,
		arg.Currency,
		arg.SettlementMode,
		arg.PayeeID,
		arg.ApplicationFee,
		arg.Metadata,
	)
	var i PaymentIntent
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.SettlementMode,
		&i.PayeeID,
		&i.ApplicationFee,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIntent = `-- name: GetIntent :one
SELECT id, merchant_id, amount, currency, status, settlement_mode, payee_id, application_fee, metadata, created_at, updated_at FROM payment_intents
WHERE id = $1 AND merchant_id = $2
`

type GetIntentParams struct {
	ID         uuid.UUID `json:"id"`
	MerchantID uuid.UUID `json:"merchant_id"`
}

// Reads are always scoped by merchant_id so one merchant can never fetch another's intent,
// even with a guessed id.
func (q *Queries) GetIntent(ctx context.Context, arg GetIntentParams) (PaymentIntent, error) {
	row := q.db.QueryRow(ctx, getIntent, arg.ID, arg.MerchantID)
	var i PaymentIntent
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.SettlementMode,
		&i.PayeeID,
		&i.ApplicationFee,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCapturedBefore = `-- name: ListCapturedBefore :many
SELECT id, merchant_id, amount, currency, status, settlement_mode, payee_id, application_fee, metadata, created_at, updated_at FROM payment_intents
WHERE status = 'captured' AND updated_at < $1
ORDER BY updated_at
LIMIT $2
`

type ListCapturedBeforeParams struct {
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	Limit     int32              `json:"limit"`
}

// The settle sweep's selection: captured intents older than the settlement delay. Only these
// settle; authorized/failed are untouched.
func (q *Queries) ListCapturedBefore(ctx context.Context, arg ListCapturedBeforeParams) ([]PaymentIntent, error) {
	rows, err := q.db.Query(ctx, listCapturedBefore, arg.UpdatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaymentIntent
	for rows.Next() {
		var i PaymentIntent
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.Amount,
			&i.Currency,
			&i.Status,
			&i.SettlementMode,
			&i.PayeeID,
			&i.ApplicationFee,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIntents = `-- name: ListIntents :many
SELECT id, merchant_id, amount, currency, status, settlement_mode, payee_id, application_fee, metadata, created_at, updated_at FROM payment_intents
WHERE merchant_id = $1
  AND ($2::text IS NULL OR status = $2)
ORDER BY created_at DESC
LIMIT $4 OFFSET $3
`

type ListIntentsParams struct {
	MerchantID uuid.UUID `json:"merchant_id"`
	Status     *string   `json:"status"`
	Off        int32     `json:"off"`
	Lim        int32     `json:"lim"`
}

// List a merchant's intents, newest first, with an optional status filter and paging. The
// status filter is a nullable arg (sqlc.narg): NULL means "no filter" — the dynamic-filter
// pattern from nem_pay/CLAUDE.md, done in plain SQL, never GORM.
func (q *Queries) ListIntents(ctx context.Context, arg ListIntentsParams) ([]PaymentIntent, error) {
	rows, err := q.db.Query(ctx, listIntents,
		arg.MerchantID,
		arg.Status,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaymentIntent
	for rows.Next() {
		var i PaymentIntent
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.Amount,
			&i.Currency,
			&i.Status,
			&i.SettlementMode,
			&i.PayeeID,
			&i.ApplicationFee,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleBefore = `-- name: ListStaleBefore :many
SELECT id, merchant_id, amount, currency, status, settlement_mode, payee_id, application_fee, metadata, created_at, updated_at FROM payment_intents
WHERE status IN ('created','requires_confirmation') AND updated_at < $1
ORDER BY updated_at
LIMIT $2
`

type ListStaleBeforeParams struct {
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	Limit     int32              `json:"limit"`
}

// The expiry sweep's selection: PRE-AUTHORIZATION intents that have sat too long. Deliberately
// excludes 'authorized' — an authorized intent holds real funds at the acquirer, and failing it
// without a bank VOID would leak that hold. Voiding is a later lesson, so authorized intents are
// left for capture (or a future void-and-expire path).
func (q *Queries) ListStaleBefore(ctx context.Context, arg ListStaleBeforeParams) ([]PaymentIntent, error) {
	rows, err := q.db.Query(ctx, listStaleBefore, arg.UpdatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaymentIntent
	for rows.Next() {
		var i PaymentIntent
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.Amount,
			&i.Currency,
			&i.Status,
			&i.SettlementMode,
			&i.PayeeID,
			&i.ApplicationFee,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockIntentForUpdate = `-- name: LockIntentForUpdate :one
SELECT id, merchant_id, amount, currency, status, settlement_mode, payee_id, application_fee, metadata, created_at, updated_at FROM payment_intents
WHERE id = $1 AND merchant_id = $2
FOR UPDATE
`

type LockIntentForUpdateParams struct {
	ID         uuid.UUID `json:"id"`
	MerchantID uuid.UUID `json:"merchant_id"`
}

// Row-lock an intent inside the money tx. Two concurrent captures both call this; the second
// BLOCKS until the first commits, then reads the already-advanced status and is rejected by the
// state machine — no double-capture, no double ledger post. Scoped by merchant for tenant safety.
func (q *Queries) LockIntentForUpdate(ctx context.Context, arg LockIntentForUpdateParams) (PaymentIntent, error) {
	row := q.db.QueryRow(ctx, lockIntentForUpdate, arg.ID, arg.MerchantID)
	var i PaymentIntent
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.SettlementMode,
		&i.PayeeID,
		&i.ApplicationFee,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateIntentStatus = `-- name: UpdateIntentStatus :one
UPDATE payment_intents
SET status = $2, updated_at = now()
WHERE id = $1
RETURNING id, merchant_id, amount, currency, status, settlement_mode, payee_id, application_fee, metadata, created_at, updated_at
`

type UpdateIntentStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

// Advance an intent's status (and bump updated_at, which the settle/expiry sweeps scan on).
func (q *Queries) UpdateIntentStatus(ctx context.Context, arg UpdateIntentStatusParams) (PaymentIntent, error) {
	row := q.db.QueryRow(ctx, updateIntentStatus, arg.ID, arg.Status)
	var i PaymentIntent
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.SettlementMode,
		&i.PayeeID,
		&i.ApplicationFee,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
