// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countUsersByEmail = `-- name: CountUsersByEmail :one
SELECT count(*) FROM users WHERE email = $1
`

// Used by the dev seed to stay idempotent (insert a user only if its email is absent).
func (q *Queries) CountUsersByEmail(ctx context.Context, email string) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersByEmail, email)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, merchant_id, email, password_hash, created_at FROM users WHERE email = $1
`

// The login lookup. Returns the bcrypt hash for the handler to compare; the raw password never
// leaves the request.
func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const insertUser = `-- name: InsertUser :one
INSERT INTO users (merchant_id, email, password_hash)
VALUES ($1, $2, $3)
RETURNING id, merchant_id, email, password_hash, created_at
`

type InsertUserParams struct {
	MerchantID   uuid.UUID `json:"merchant_id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, insertUser, arg.MerchantID, arg.Email, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}
